### ISSUE TITLE
references

### ISSUE THREAD

**Issue by supermanas** [KrishnaMoorthy12/portfolio-v2#50]
hello sir, supermanas this side grade 10th student ,would request you to remove my name under your references termed as shamefull .i apologise for my mistake and have made the repository private

**Comment by KrishnaMoorthy12** [comment]
Hi Manas. I appreciate that you're trying to get things right, but making your repository private doesn't change anything, because you still clearly do claim the work as yours on your site.

```
Designed and built
by manas kumar
```

You can use the design and code as long as mention my name as the original author. Also, note that I won't claim attribution if the shape and design of the site have changed beyond recognizable similarity. 

I'm fascinated that a kid as young as you know this much already, and I'm sure you can put together your very own site, probably even better than mine someday. I request you to attribute to me as long as you use my work. As you can probably guess/ have read, I have put in a significant amount of effort and time into building this and I want recognition for that.

**Comment by supermanas** [comment]
once again i apologize for my mistake and understood the use of the platform and have attributed you on the footer tab and. hope you have forgiven me and will remove that comment! thank you :). also i would soon change the theme and would create something unique

**Comment by KrishnaMoorthy12** [comment]
> once again i apologize for my mistake and understood the use of the platform and have attributed you on the footer tab and. hope you have forgiven me and will remove that comment! thank you :). also i would soon change the theme and would create something unique

Thanks <3 and all the best for your career.
